"""Initial migration

Revision ID: 2260e97a70b4
Revises: 4006affb13b1
Create Date: 2023-06-13 12:39:12.713398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2260e97a70b4'
down_revision = '4006affb13b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
