"""Initial migration

Revision ID: 4006affb13b1
Revises: 85afcf9a01f7
Create Date: 2023-06-07 16:35:24.989433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4006affb13b1'
down_revision = '85afcf9a01f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
