"""Initial migration

Revision ID: 85afcf9a01f7
Revises: 
Create Date: 2023-06-05 10:13:15.406121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85afcf9a01f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
